services:
  db:
    image: postgres:16
    container_name: postgres_portfolio
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: portfolio_app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8082:8082"
    networks:
      - portfolio_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_portfolio
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - portfolio_network

volumes:
  postgres_data:

networks:
  portfolio_network:
    driver: bridge